apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: green-app
---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: blue-app
