apiVersion: v1
kind: Secret
metadata:
  name: green-secrets
type: Opaque
data:
  db-password:
    ewogICJEYXRhYmFzZSI6ewogICAgIlBhc3N3b3JkIjogImRvbnQtbG9vay1hdC1tZSEiCiAgfQp9Cg==
    # the above is base 64 for
    #{
    #  "Database":{
    #    "Password": "dont-look-at-me!"
    # }
    #}
